# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f9272498b54681eda37fed9478a3065aed2a6fe1d91f9b72cee7169deebd6c095e78ace5a70e13d10b0135364b0fed0c84af9b7c1613503b3e7bd0ab47111a0

test:
  secret_key_base: d8594cfe3cf9e3cd1fe532734bbc167e88c9f5dcfdb262f6955bf51fc60b3a1ad2256fb43ba474f71eefb51ef3c7542a727f03fbee11e47f82f5b774105a1948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
